# ISO date
app.schedule.start-date=2025-04-01

# ISO time
app.schedule.start-time=14:30:00

# Custom date?time (slash + space)
app.schedule.deadline=2025/04/30 18:00

# Instant in UTC
app.schedule.instant=2025-04-01T14:30:00Z

# Zoned date?time with offset
app.schedule.zoned=2025-04-01 14:30:00+0200